# MoveIt uses this configuration for controllers
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# Real ros2_control execution
moveit_simple_controller_manager:
  controller_names:
    - sekirei_arm_controller

  sekirei_arm_controller:
    type: FollowJointTrajectory
    # ros2_control publishes actions at /controller_name/follow_joint_trajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - arm_joint6
