repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# Optional â€” re-enable Black later if needed
# -   repo: https://github.com/psf/black
#     rev: 25.9.0
#     hooks:
#     -   id: black

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
    -   id: clang-format
        # ROS2 C++ files only (in ros_ws/src/)
        files: ^ros_ws/src/.*\.(cpp|hpp|h|cc|cxx)$
        exclude: |
          (?x)^(
              ros_ws/src/eProsima/.*|
              ros_ws/src/ros2/.*|
              ros_ws/src/micro_ros_setup/.*|
              microros_ws/firmware/toolchain/.*|
              \.local/.*|
              \.cache/.*|
              \.venv/.*|
              env/.*|
              .*/build/.*|
              .*/install/.*|
              .*/log/.*
          )$
